#! /bin/sh
# Copies the basic exemplars to user's home area then launches
# prj and opens the 3-zone model with convective heating and ideal
# control. Used for the first hands-on in the network air flow course.

cd $HOME
cp -r /users/espcourse/hands-on-files/esp-r_files/airflow2 airflow2
cd $HOME/airflow2/cfg
hot3000 -file bld_basic.cfg -s 80,0,0
